### ISSUE TITLE
Can't compile with libxml2 2.9

### ISSUE THREAD

**Issue by GoogleCodeExporter** [prest3/php52-backports#16]
```
Error follows:

ext/dom/node.c: In function 'dom_canonicalization':
ext/dom/node.c:1953:21: error: dereferencing pointer to incomplete type
ext/dom/node.c:1955:5: error: dereferencing pointer to incomplete type
make: *** [ext/dom/node.lo] Error 1

looks like something with buf->buffer class ;/
```

Original issue reported on code.google.com by `romans.h...@gmail.com` on 25 Mar 2013 at 11:14
